services:
  db:
    image: postgis/postgis:14-3.5
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: homes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_NAME: homes
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "False"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: > 
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data: